[global]
root_path_unix = "/tmp/iceoryx2/"
prefix = "iox2_"

[service]
creation_timeout = "2000ms"

[defaults.publish_subscribe]
max_subscribers = 16
max_publishers = 512
max_nodes = 1024
subscriber_max_buffer_size = 256
publisher_history_size = 16
